version: 3.2.1.{build}
image: Visual Studio 2022

environment:
  VS_VERSION: vs2022
  BUILD_CHAIN_DIR: c:\build_chain\libffi


branches:
  only:
    - master

platform:
- x86
- x64

configuration: Release

build:
  parallel: true
  project: libffi.sln 
  verbosity: normal


notifications:
- provider: Email
  to:
  - nelson.numerical.computation@gmail.com

# clone directory
clone_folder: c:\build_chain\libffi

